server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: "zixieqing072413"
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis:
  type-aliases-package: com.zixieqing.user.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.zixieqing: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
ribbon:
  eager-load:
    # 开启负载均衡恶汉加载模式
    enabled: true
    # clients是一个String类型的List数组，多个时采用下面的 - xxxx服务 的形式
    clients:
      - userservice
feign:
  httpclient:
    # 开启feign对HttpClient的支持		默认值就是true，即导入对应客户端依赖之后就开启了，但为了提高代码可读性，还是显示声明比较好
    enabled: true
    # 最大的连接数
    max-connections: 200
    # 每个路径最大连接数
    max-connections-per-route: 50
    # 链接超时时间
    connection-timeout: 2000
    # 存活时间
    time-to-live: 900