server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: "zixieqing072413"
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: ORDER-SERVICE
  # 另一个和 @EnableEurekaClient 注解差不多等价的配置
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: true
mybatis:
  type-aliases-package: com.zixieqing.user.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.zixieqing: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:
      # 向那个eureka服务端进行服务注册
      defaultZone: http://localhost:10086/eureka
#    # 开启eureka client功能，默认就是true，差不多等价于启动类中加 @EnableEurekaClient 注解
#    #enabled: true
    # 单独对某个服务设置负载均衡策略
#USER-SERVICE:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#ribbon:
#  eager-load:
#    # 开启负载均衡恶汉加载模式
#    enabled: true
#    # clients是一个String类型的List数组，多个时采用下面的 - xxxx服务 的形式
#    clients:
#      - USER-SERVICE