server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: "zixieqing072413"
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      # Nacos服务器地址，本地启动的Nacos
      server-addr: localhost:8848
mybatis:
  type-aliases-package: com.zixieqing.user.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.zixieqing: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS