server:
  port: 10086
spring:
  application:
    name: EUREKA-SERVER
eureka:
  instance:
    # 此机Eureka的主机名，eureka集群服务器之间的区分
    hostname: localhost
    # 最后一次心跳后，间隔多久认定微服务不可用，默认90
#    lease-expiration-duration-in-seconds: 90
  client:
    # 不向自身注册。应用为单个注册中心设置为false，代表不向注册中心注册自己，默认true
#    registerWithEureka: false
    # 不从自身拉取注册信息。单个注册中心，不拉去自身信息，默认true
#    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
#  server:
#    renewal-percent-threshold: 0.85
#    server:
#      # 开启Eureka自我保护机制，默认为true
#      enable-self-preservation: true